### Add an user
POST {{urlGateway}}/users
Content-Type:application/json

{
  "email": "gregory.seront@vinci.be",
  "firstName": "Gregory",
  "lastName": "Seront",
  "password": "password123"
}

### Get an user
GET {{urlGateway}}/users/1