### Create user1
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "nada2@gmail.com",
  "firstname": "nada",
  "lastname": "nada",
  "password": "123"
}

### Create user2
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "chaymae@gmail.com",
  "firstname": "chaymae",
  "lastname": "chaymae",
  "password": "123"
}



### Connect user1
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "nada2@gmail.be",
  "password": "123"
}

> {% client.global.set("token", response.body) %}

### Connect user2
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "chaymae@gmail.be",
  "password": "123"
}
> {% client.global.set("token", response.body) %}

###Get user notifications
GET http://localhost:8080/user/1/notifications
Authorization: {{token}}




