### Test creat new credentials with valide data
POST http://localhost:9004/auth/user.email@validebe
Content-Type: application/json

{
  "email":"user.email@validebe",
  "password": "password"
}


### auth from gateway
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email":"user.email@validebe",
  "password": "password"
}

### Test creat new credentials with unvalide data
POST http://localhost:9004/auth/user
Content-Type: application/json

{
  "email":"",
  "password": ""
}

###Test connexion with validated credentials
POST http://localhost:9004/auth/connect
Content-Type: application/json

{
  "email":"user.email@validebe",
  "password": "password"
}
> {%
client.global.set("token", response.body.token);
%}

###Test connexion with unvalidated credentials
POST http://localhost:9004/auth/connect
Content-Type: application/json

{
  "email":"user.email@validebe",
  "password": "wrongpassword"
}

### verify
POST http://localhost:9004/auth/verify
Content-Type: application/json

{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoidXNlci5lbWFpbEB2YWxpZGViZSJ9.Fsq33LTsF6kRmdi-dBziWquAVsWN5WTOEP15I8C41xhKqi1kAVkpZ_J0hfwrA7VEZqRwWDpEpSdbI0CW_-sDdw"
}

### update user's password
PUT http://localhost:9004/auth/user.email@validebe
Content-Type: application/json

{
  "email":"user.email@validebe",
  "password": "password"
}

###
DELETE http://localhost:9004/auth/{{email}}

