openapi: 3.0.3
info:
  title: Chatty car authentication service
  description: Microservice handling authentication and credentials
  version: 1.0.0
servers:
  - url: 'http://localhost:9002'
    description: Development server
paths:
  /auth/{email}:
    parameters:
      - name: email
        required: true
        in: path
        description: Email of the user
        schema:
          type: string
    post:
      summary: Create credentials
      requestBody:
        description: Credentials of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        400:
          description: Incorrect credentials
        409:
          description: Credentials already exists
        201:
          description: Credentials created

    put:
      summary: Update user's password
      requestBody:
        description: Credentials of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        400:
          description: Incorrect credentials
        404:
          description: Credentials not found
        200:
          description: Credentials updated

    delete:
      summary: Delete credentials
      responses:
        400:
          description: Incorrect credentials
        404:
          description: Credentials not found
        200:
          description: Credentials deleted
  /auth/connect:
    post:
      summary: Connect user and retrieve authentication JWT token
      requestBody:
        description: Credentials of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        400:
          description: Credentials in request are not correct
        401:
          description: Wrong username or password
        200:
          description: User authenticated, sent JWT token
          content:
            'text/plain':
              schema:
                type: string
                example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoMCIsInBzZXVkbyI6IkNhdDRMaWZlIn0.LqfooEI-I9VTBo-isjm812ttnIPagMCwdhRkW5ngn0_tlLX86LRoxahgskmgIeWDbm4Mu3y3D8Qbhq_71hNQTA
  /auth/verify:
    post:
      summary: Verify user's token
      requestBody:
        description: Credentials of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        401:
          description: Token couldn't be verified
        200:
          description: Token verified, returned user email
          content:
            'application/json':
              schema:
                type: string
                example: chattyCar
components:
  schemas:
    credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: gregory.seront@vinci.be
        password: password123